# Generated by Django 5.1.3 on 2024-11-22 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_saff',
            new_name='is_staff',
        ),
    ]
